### ISSUE TITLE
Welcome title and text should be configurable without partial override

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-public#230]
Needed for the protected data network.

/cc @jt112

**Comment by jt112** [comment]
Welcome to Duke Protected Data Repository
 
The Duke Protected Data Repository (PDR) provides secure preservation and limited access to protected and sensitive digital assets. Duke Protected Data Repository is a service of Duke University Libraries.

For further information or assistance please contact repository-help@duke.edu


/cc @dchandekstark

**Comment by corylown** [comment]
This was implemented in v2.0.0.

In config/locales/en.yml add the following to override the default text:

```
en:
    ddr:
        public:
            portal:
                catalog:
                    title: "Welcome to Duke Protected Data Repository"
                    about: "The Duke Protected Data Repository (PDR) provides secure preservation and limited access to protected and sensitive digital assets. Duke Protected Data Repository is a service of Duke University Libraries."
```
